import { IAoCInput } from "../../../utils/javascript/deno-utils/input.ts";

export const input: IAoCInput = {
  "year": 2021,
  "day": 12,
  "input": [
    "CI-hb",
    "IK-lr",
    "vr-tf",
    "lr-end",
    "XP-tf",
    "start-vr",
    "lr-io",
    "hb-qi",
    "end-CI",
    "tf-YK",
    "end-YK",
    "XP-lr",
    "XP-vr",
    "lr-EU",
    "tf-CI",
    "EU-vr",
    "start-tf",
    "YK-hb",
    "YK-vr",
    "start-EU",
    "lr-CI",
    "hb-XP",
    "XP-io",
    "tf-EU",
  ],
};
